require('lazy').setup({
  spec = {
    { import = "plugins.snacks" },
    { import = "plugins.nvim-tree" },
    { import = "plugins.telescope" },
    { import = "plugins.nvim-lspconfig" },
    { import = "plugins.blink-cmp" },
    { import = "plugins.nvim-autopairs" },
    { import = "plugins.bufferline" },
    { import = "plugins.nvim-treesitter" },
    { import = "plugins.sidekick" },
    { import = "plugins.kanagawa" },
    { import = "plugins.nvim-tmux-navigator" },
    { import = "plugins.which-key" },
    { import = "plugins.alpha" },
    { import = "plugins.auto-session" },
    { import = "plugins.lualine" },
    { import = "plugins.dressing" },
    { import = "plugins.vim-maximizer" },
    { import = "plugins.comment" },
    { import = "plugins.todo-comments" },
    { import = "plugins.substitute" },
    { import = "plugins.nvim-surround" },
    { import = "plugins.trouble" },
    { import = "plugins.formatting" },
    { import = "plugins.nvim-lint" },
    { import = "plugins.gitsigns" },
    { import = "plugins.indent-blankline" },
    { import = "plugins.flash" },
    { import = "plugins.nvim-dap" },
    -- { import = "plugins.tokyonight" }
  },
})
